mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from polls import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views
from debug_toolbar.toolbar import debug_toolbar_urls

app_name='polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/result/', views.ResultView.as_view(), name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
] + debug_toolbar_urls()

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

class Books(models.Model):
    bookname=models.CharField(max_length=50)
    price=models.FloatField(max_length=10)
    
class Questions(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    
    @admin.display(
            boolean=True,
            ordering='pub_date',
            description='Published recently?',
    )
    def was_publishedrecently(self):
        now=timezone.now()
        return now-datetime.timedelta(days=1)<=self.pub_date<=now
        
    
class Choice(models.Model):
    question=models.ForeignKey("Questions",on_delete=models.CASCADE)
    choice_field=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_field
    

mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Questions,Choice
from django.template import loader
from django.db.models import F
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name="polls/index.html"
    context_object_name="latest_questions_list" 

    def get_queryset(self):
        return Questions.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:5]

class DetailView(generic.DetailView):
    template_name='polls/detail.html'
    context_object_name='question'
    
    def get_queryset(self):
        return Questions.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:5]
    

class ResultView(generic.DetailView):
    template_name='polls/result.html'
    context_object_name='question'

    def get_queryset(self):
        return Questions.objects.filter(pub_date__lte=timezone.now())
    




def vote(request,question_id):
    question=get_object_or_404(Questions,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{'question':question,'error_message':"you didn't select choice"})
    else:
        selected_choice.votes=F('votes')+1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:result',args=(question.id,)))

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}">{{choice.choice_field}}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}"
{% if latest_questions_list %}
    <ul>
        {% for question in latest_questions_list %}
            <li><a href="/polls/{{question.id}}/">
                {{question.question_text}}
            </a>
            </li>
        {% endfor%}
    </ul>
{% else %}
    <p> No polls are available </p>
{% endif %}

mysite/polls/templates/polls/result.html
<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_field}}--{{choice.votes}}votes</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>